USE [QLDSV_TC]
GO

CREATE PROC [dbo].[SP_DSHOCPHI]
@MASV NCHAR(10)
AS
BEGIN
	SELECT  HP.NIENKHOA,HP.HOCKY, HP.HOCPHI, ISNULL(TONGTIENDADONG,0) AS TONGTIENDADONG
	FROM ((SELECT NIENKHOA, HOCKY,HOCPHI FROM HOCPHI WHERE MASV = @MASV) HP
	LEFT JOIN (SELECT NIENKHOA, HOCKY,TONGTIENDADONG=SUM(CTDHP.SOTIENDONG) FROM CT_DONGHOCPHI CTDHP WHERE MASV = @MASV 
	GROUP BY CTDHP.NIENKHOA, CTDHP.HOCKY) CTDHP ON HP.NIENKHOA = CTDHP.NIENKHOA  AND HP.HOCKY = CTDHP.HOCKY)
END

GO


