USE [QLDSV_TC]
GO

CREATE PROCEDURE SP_HOCPHICONLAI_HOCPHI
    @MASV NVARCHAR(10),
    @NIENKHOA NVARCHAR(9),
    @HOCKY INT
AS
BEGIN
    DECLARE @MASV_TRIM NVARCHAR(10);
    SET @MASV_TRIM = LTRIM(RTRIM(@MASV));

    IF NOT EXISTS (
        SELECT 1
        FROM SINHVIEN
        WHERE MASV = @MASV_TRIM
    )
    BEGIN
        RAISERROR (N'Sinh viên "%s" không tồn tại trong hệ thống.', 16, 1, @MASV_TRIM);
        RETURN;
    END

    IF EXISTS (
        SELECT 1
        FROM SINHVIEN
        WHERE MASV = @MASV_TRIM AND DANGHIHOC = 1
    )
    BEGIN
        RAISERROR (N'Sinh viên "%s" đã nghỉ học.', 16, 1, @MASV_TRIM);
        RETURN;
    END

    SELECT
        (HP.HOCPHI - ISNULL(CT.TONG_DA_DONG, 0)) AS SOTIENCONLAI,
        HP.HOCPHI
    FROM
        (SELECT MASV, NIENKHOA, HOCKY, HOCPHI
         FROM HOCPHI
         WHERE MASV = @MASV
           AND NIENKHOA = @NIENKHOA
           AND HOCKY = @HOCKY
        ) HP
    LEFT JOIN
        (SELECT MASV, NIENKHOA, HOCKY, SUM(SOTIENDONG) AS TONG_DA_DONG
         FROM CT_DONGHOCPHI
         WHERE MASV = @MASV
           AND NIENKHOA = @NIENKHOA
           AND HOCKY = @HOCKY
         GROUP BY MASV, NIENKHOA, HOCKY
        ) CT
        ON  CT.MASV = HP.MASV
        AND CT.NIENKHOA = HP.NIENKHOA
        AND CT.HOCKY = HP.HOCKY;
END

GO


