USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[sp_Insert_CT_DONGHOCPHI]    Script Date: 13/12/2025 4:27:03 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_CTDONGHOCPHI]
    @MASV        NVARCHAR(10),
    @NIENKHOA    NVARCHAR(9),
    @HOCKY       INT,
    @NGAYDONG    DATE,
    @SOTIENDONG  INT
AS

BEGIN

    IF EXISTS (SELECT 1 FROM CT_DONGHOCPHI WHERE MASV = @MASV AND NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND NGAYDONG = @NGAYDONG)
    BEGIN
        RAISERROR(N'D? li?u ?óng h?c phí ?ã t?n t?i!',16,1);
        RETURN;
    END

    INSERT INTO CT_DONGHOCPHI (MASV,NIENKHOA,HOCKY,NGAYDONG,SOTIENDONG)
    VALUES(@MASV,@NIENKHOA,@HOCKY,@NGAYDONG,@SOTIENDONG);
END
GO


EXEC dbo.SP_INSERT_CTDONGHOCPHI
    @MASV = 'N15DCCN001',
    @NIENKHOA = '2021-2022',
    @HOCKY = 1,
    @NGAYDONG = '2025-01-15',
    @SOTIENDONG = 3500000;