USE [QLDSV_TC]
GO

CREATE PROCEDURE [dbo].[SP_INSERT_CTDONGHOCPHI]
    @MASV        NVARCHAR(10),
    @NIENKHOA    NVARCHAR(9),
    @HOCKY       INT,
    @NGAYDONG    DATE,
    @SOTIENDONG  INT
AS

BEGIN

    IF EXISTS (SELECT 1 FROM CT_DONGHOCPHI WHERE MASV = @MASV AND NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND NGAYDONG = @NGAYDONG)
    BEGIN
        RAISERROR(N'Sinh viên đã đóng học phí trong ngày. Không thể đóng thêm.',16, 1);
        RETURN;
    END

    INSERT INTO CT_DONGHOCPHI (MASV,NIENKHOA,HOCKY,NGAYDONG,SOTIENDONG)
    VALUES(@MASV,@NIENKHOA,@HOCKY,@NGAYDONG,@SOTIENDONG);
END
GO


