CREATE PROC SP_LAY_THONGTIN_SV
@MASV NCHAR(10)
AS
	
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SINHVIEN WHERE MASV = @MASV)
    BEGIN
        RAISERROR ('Mã sinh viên không t?n t?i!', 16, 1);
        RETURN;
    END

    SELECT 
        HO + ' ' + TEN AS HOTEN,
        MALOP
    FROM SINHVIEN
    WHERE MASV = @MASV;
END
GO

exec dbo.SP_LAY_THONGTIN_SV N'N15DCCN001'