USE [QLDSV_TC]
GO

CREATE PROC SP_LAYDS_HOCPHI
@MASV NCHAR(10)
AS
BEGIN
	DECLARE @MASV_TRIM NVARCHAR(10);
    SET @MASV_TRIM = LTRIM(RTRIM(@MASV));

    IF NOT EXISTS (
        SELECT 1
        FROM SINHVIEN
        WHERE MASV = @MASV_TRIM
    )
    BEGIN
        RAISERROR (N'Sinh viên "%s" không tồn tại trong hệ thống.', 16, 1, @MASV_TRIM);
        RETURN;
    END

    IF EXISTS (
        SELECT 1
        FROM SINHVIEN
        WHERE MASV = @MASV_TRIM AND DANGHIHOC = 1
    )
    BEGIN
        RAISERROR (N'Sinh viên "%s" đã nghỉ học.', 16, 1, @MASV_TRIM);
        RETURN;
    END


	SELECT  HP.NIENKHOA,HP.HOCKY, HP.HOCPHI, ISNULL(TONGTIENDADONG,0) AS TONGTIENDADONG
	FROM ((SELECT NIENKHOA, HOCKY,HOCPHI FROM HOCPHI WHERE MASV = @MASV) HP
	LEFT JOIN (SELECT NIENKHOA, HOCKY,TONGTIENDADONG=SUM(CTDHP.SOTIENDONG) FROM CT_DONGHOCPHI CTDHP WHERE MASV = @MASV 
	GROUP BY CTDHP.NIENKHOA, CTDHP.HOCKY) CTDHP ON HP.NIENKHOA = CTDHP.NIENKHOA  AND HP.HOCKY = CTDHP.HOCKY)
END

GO


