USE [QLDSV_TC]
GO


CREATE PROCEDURE SP_TAO_CTDONGHOCPHI
    @MASV        NVARCHAR(10),
    @NIENKHOA    NVARCHAR(9),
    @HOCKY       INT,
    @NGAYDONG    DATE,
    @SOTIENDONG  INT
AS

BEGIN
    DECLARE @NGAYCUOI NVARCHAR(20);
    SET @NGAYCUOI = CONVERT(NVARCHAR(10), @NGAYDONG, 103);

    DECLARE @MASV_TRIM NVARCHAR(10);
    SET @MASV_TRIM = LTRIM(RTRIM(@MASV));

    IF NOT EXISTS (
        SELECT 1
        FROM SINHVIEN
        WHERE MASV = @MASV_TRIM
    )
    BEGIN
        RAISERROR (N'Sinh viên "%s" không tồn tại trong hệ thống.', 16, 1, @MASV_TRIM);
        RETURN;
    END

    IF EXISTS (
        SELECT 1
        FROM SINHVIEN
        WHERE MASV = @MASV_TRIM AND DANGHIHOC = 1
    )
    BEGIN
        RAISERROR (N'Sinh viên "%s" đã nghỉ học.', 16, 1, @MASV_TRIM);
        RETURN;
    END


    IF EXISTS (SELECT 1 FROM CT_DONGHOCPHI WHERE MASV = @MASV AND NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND NGAYDONG = @NGAYDONG)
    BEGIN
        RAISERROR(N'Đã đóng học phí ngày "%s". Vui lòng đợi đến ngày mai để thực hiện đóng học phí tiếp theo.',16, 1, @NGAYCUOI);
        RETURN;
    END

    INSERT INTO CT_DONGHOCPHI (MASV,NIENKHOA,HOCKY,NGAYDONG,SOTIENDONG)
    VALUES(@MASV,@NIENKHOA,@HOCKY,@NGAYDONG,@SOTIENDONG);
END
GO