USE [QLDSV_TC]
GO

CREATE PROCEDURE [dbo].[SP_UPDATE_CTDONGHOCPHI]
    @MASV        NVARCHAR(10),
    @NIENKHOA    NVARCHAR(9),
    @HOCKY       INT,
    @NGAYDONG    DATE,
    @SOTIENDONG  INT
AS

BEGIN

    IF NOT EXISTS (SELECT 1 FROM CT_DONGHOCPHI WHERE MASV = @MASV AND NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND NGAYDONG = @NGAYDONG)
    BEGIN
        RAISERROR(N'Không tìm thấy dữ liệu để cập nhật!',16,1);
        RETURN;
    END

    UPDATE CT_DONGHOCPHI
    SET SOTIENDONG = @SOTIENDONG
    WHERE MASV = @MASV
      AND NIENKHOA = @NIENKHOA
      AND HOCKY = @HOCKY
      AND NGAYDONG = @NGAYDONG;
END
GO


