USE [QLDSV_TC]
GO

CREATE PROC SP_CHECK_TAOLOP
@MALOP NCHAR(10),
@TENLOP NVARCHAR(50)
AS 
    DECLARE @MALOP_TRIM NVARCHAR(10);
    SET @MALOP_TRIM = LTRIM(RTRIM(@MALOP));

    IF EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP_TRIM)
    BEGIN
        RAISERROR(N'Mã lớp "%s" đã tồn tại trên Khoa hiện tại!', 16, 1, @MALOP_TRIM);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM LINK0.QLDSV_TC.dbo.LOP WHERE MALOP = @MALOP_TRIM)
    BEGIN
        RAISERROR(N'Mã lớp "%s" đã tồn tại trên Khoa còn lại!', 16, 1, @MALOP_TRIM);
        RETURN;
    END


    DECLARE @TENLOP_TRIM NVARCHAR(50);
    SET @TENLOP_TRIM = LTRIM(RTRIM(@TENLOP));

    IF EXISTS (SELECT 1 FROM LOP WHERE TENLOP =  @TENLOP_TRIM)
    BEGIN
        RAISERROR(N'Tên lớp "%s" đã tồn tại trên Khoa hiện tại!', 16, 1,  @TENLOP_TRIM);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM LINK0.QLDSV_TC.dbo.LOP WHERE TENLOP = @TENLOP_TRIM)
    BEGIN
        RAISERROR(N'Tên lớp "%s" đã tồn tại trên Khoa còn lại!', 16, 1, @TENLOP_TRIM);
        RETURN;
    END
GO


