USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSLTC_DSSVDKLTC]    Script Date: 01/12/2025 6:16:33 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROC [dbo].[SP_DSLTC_DSSVDKLTC]
@NIEMKHOA NCHAR(10),
@HOCKY INT,
@MASV NCHAR(10)

AS
BEGIN
	SELECT ROW_NUMBER() over(ORDER BY MH.TENMH, LTC.NHOM) STT,
	LTC.MAMH,
	TENMH,
	NIENKHOA,
	HOCKY,NHOM, 
	LTC.MALTC
	FROM (SELECT MALTC FROM DANGKY WHERE MASV = @MASV AND HUYDANGKY = 0) DS
	INNER JOIN (SELECT MALTC,MAMH,NIENKHOA,HOCKY,NHOM FROM LOPTINCHI) LTC ON DS.MALTC = LTC.MALTC
	INNER JOIN (SELECT MAMH,TENMH FROM MONHOC) MH ON LTC.MAMH = MH.MAMH
	WHERE NIENKHOA = @NIEMKHOA AND HOCKY = @HOCKY 
END

GO


