USE [QLDSV_TC]
GO



ALTER PROC [dbo].[SP_DANGKY_LTC]
    @MASV  NCHAR(10),
    @MALTC INT
AS
BEGIN
    

    IF NOT EXISTS (SELECT 1  FROM DANGKY WHERE MALTC = @MALTC AND MASV = @MASV)
    BEGIN
        INSERT INTO DANGKY (MALTC, MASV, HUYDANGKY)
        VALUES (@MALTC, @MASV, 0);
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM DANGKY WHERE MALTC = @MALTC AND MASV  = @MASV AND HUYDANGKY IS NULL)
    BEGIN
        UPDATE DANGKY
        SET HUYDANGKY = 1
        WHERE MALTC = @MALTC AND MASV = @MASV;
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM DANGKY WHERE MALTC = @MALTC AND MASV  = @MASV AND HUYDANGKY=0)
    BEGIN
        RAISERROR (N'Sinh viên đã đã đăng ký lớp tín chỉ này rồi.', 16, 1);
        RETURN;
    END

    RAISERROR (N'Sinh viên đã hủy lớp tín chỉ này rồi.', 16, 1);
END
GO


