USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DSLTC_NIENKHOAHOCKY]    Script Date: 02/12/2025 10:06:47 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC SP_DSLTC_NIENKHOAHOCKY
@NIEMKHOA NCHAR(10),
@HOCKY INT

AS
BEGIN
	SELECT 
        STT=ROW_NUMBER() OVER(ORDER BY MH.MAMH,NHOM),
        MH.MAMH, 
        MH.TENMH, 
        NHOM, 
        TENGV=(SELECT HO + ' ' + TEN FROM GIANGVIEN WHERE LTC.MAGV = GIANGVIEN.MAGV),
        SOSVTOITHIEU,
        SOSVDADK = COUNT(DK.MASV),  
        LTC.MALTC

    FROM LOPTINCHI LTC
    LEFT JOIN (SELECT MAMH, TENMH FROM MONHOC) MH ON LTC.MAMH = MH.MAMH
    LEFT JOIN (SELECT MALTC, MASV FROM DANGKY WHERE HUYDANGKY = 0 OR DANGKY.HUYDANGKY IS NULL) DK ON DK.MALTC = LTC.MALTC
    WHERE LTC.NIENKHOA = @NIEMKHOA and LTC.HOCKY = @HOCKY and LTC.HUYLOP = 0 OR LTC.HUYLOP IS NULL
    GROUP BY MH.MAMH, MH.TENMH, NHOM,LTC.MAGV, SOSVTOITHIEU,LTC.MALTC

END

GO


