USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DANGKY_LTC]    Script Date: 09/12/2025 12:37:55 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SP_DANGKY_LTC]
@MASV NCHAR(10), @MALTC INT
AS
BEGIN
	IF EXISTS(SELECT * FROM DANGKY WHERE MALTC = @MALTC AND MASV = @MASV)
		BEGIN
			UPDATE DANGKY SET HUYDANGKY = 0 WHERE MALTC = @MALTC AND MASV = @MASV
		END
	ELSE
		BEGIN
			INSERT INTO DANGKY(MALTC,MASV, HUYDANGKY)
			VALUES (@MALTC, @MASV, 1)
		END
END
GO


