USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_HUYDANGKY_LTC]    Script Date: 09/12/2025 12:39:37 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SP_HUYDANGKY_LTC]
@MASV NCHAR(10), @MALTC INT
AS
BEGIN
	UPDATE DANGKY SET HUYDANGKY = 1 WHERE MALTC = @MALTC AND MASV = @MASV
END
GO


