USE [QLDSV_TC]
GO

CREATE PROC SP_LAY_HOTENSV
@MASV NCHAR(10)
AS
BEGIN
	SELECT HOTEN = HO + ' ' +  TEN, L.MALOP, L.TENLOP, L.MAKHOA FROM SINHVIEN SV, LOP L WHERE MASV = @MASV AND SV.MALOP = L.MALOP
END

GO


