USE [QLDSV_TC]
GO

CREATE PROC SP_CAPNHAT_NHAPDIEM
    @DIEMTHI TYPE_DANGKY READONLY
AS
BEGIN
    MERGE INTO DANGKY AS TARGET
    USING (
        SELECT MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK
        FROM @DIEMTHI
    ) AS SOURCE
        ON TARGET.MALTC = SOURCE.MALTC
       AND TARGET.MASV  = SOURCE.MASV

    WHEN MATCHED THEN
        UPDATE SET 
            TARGET.DIEM_CC = SOURCE.DIEM_CC,
            TARGET.DIEM_GK = SOURCE.DIEM_GK,
            TARGET.DIEM_CK = SOURCE.DIEM_CK

    WHEN NOT MATCHED BY TARGET THEN
        INSERT (MALTC, MASV, DIEM_CC, DIEM_GK, DIEM_CK)
        VALUES (SOURCE.MALTC, SOURCE.MASV, SOURCE.DIEM_CC, SOURCE.DIEM_GK, SOURCE.DIEM_CK);

END
GO


