USE [QLDSV_TC]
GO

CREATE PROCEDURE SP_CHECK_CAPNHATLOPTINCHI
    @MALTC int
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM LOPTINCHI WHERE MALTC = @MALTC)
    BEGIN
        RAISERROR ( N'Lớp tín chỉ không tồn tại.',16, 1);
        RETURN;
    END
END
GO
