CREATE PROC SP_CHECKTMAMH
@MAMH NVARCHAR(50)
AS
BEGIN
	IF EXISTS(SELECT * FROM MONHOC WHERE MAMH = @MAMH)
		SELECT KT = 1
	ELSE 
		IF EXISTS(SELECT * FROM LINK0.QLDSV_TC.DBO.MONHOC WHERE MAMH = @MAMH)	
			SELECT KT = 1
		ELSE
			SELECT KT = 0
END
GO