CREATE PROC SP_CHECK_LTC
@NIENKHOA NCHAR(9), @MAMH NCHAR(10), @NHOM INT, @HOCKY INT
AS
BEGIN
	IF EXISTS(SELECT MALTC FROM LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND MAMH = @MAMH AND NHOM = @NHOM AND HOCKY = @HOCKY)
		SELECT KT = 1
	ELSE
		IF EXISTS(SELECT MALTC FROM LINK0.QLDSV_TC.DBO.LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND MAMH = @MAMH AND NHOM = @NHOM AND HOCKY = @HOCKY)
			SELECT KT = 1
		ELSE
			SELECT KT = 0
END
GO