CREATE PROC SP_CHECKMASINHVIEN
@MSV NCHAR(10)
AS
BEGIN
	IF EXISTS(SELECT MASV FROM DBO.SINHVIEN WHERE MASV = @MSV)
	BEGIN
		SELECT 'SV' = 1 
	END
ELSE
IF EXISTS(SELECT MASV FROM LINK0.QLDSV_TC.DBO.SINHVIEN WHERE MASV = @MSV)
	BEGIN
		SELECT 'SV' = 2
	END
ELSE
	SELECT 'SV' = 0
END
GO
