CREATE PROC SP_DSLTC
@NK NCHAR(9), @HK INT
AS
BEGIN
	SELECT STT=ROW_NUMBER() OVER(ORDER BY MH.MAMH,NHOM), MH.TENMH, NHOM, 
	TENGV=(SELECT HO + ' ' + TEN FROM GIANGVIEN WHERE LOPTINCHI.MAGV = GIANGVIEN.MAGV), SOSVTOITHIEU, 
	SOSVDADK = COUNT(DK.MASV)

	FROM LOPTINCHI
	LEFT JOIN (SELECT MAMH, TENMH FROM MONHOC) MH 
	ON LOPTINCHI.MAMH = MH.MAMH

	LEFT JOIN (SELECT MALTC, MASV FROM DANGKY WHERE HUYDANGKY = 0) DK 
	ON DK.MALTC = LOPTINCHI.MALTC

	WHERE LOPTINCHI.NIENKHOA = @NK and LOPTINCHI.HOCKY = @HK and LOPTINCHI.HUYLOP = 0 
	GROUP BY MH.MAMH, MH.TENMH, NHOM,LOPTINCHI.MAGV, SOSVTOITHIEU
END

EXEC SP_DSLTC '2021-2022', 1