USE [QLDSV_TC]
GO

CREATE PROC SP_CHECK_LTC
@NIENKHOA NCHAR(9), @MAMH NCHAR(10), @NHOM INT, @HOCKY INT
AS
BEGIN
	IF EXISTS(SELECT MALTC FROM LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND MAMH = @MAMH AND NHOM = @NHOM AND HOCKY = @HOCKY)
		BEGIN
			SELECT KT = 1
		END
	ELSE
		IF EXISTS(SELECT MALTC FROM LINK0.QLDSV_TC.DBO.LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND MAMH = @MAMH AND NHOM = @NHOM AND HOCKY = @HOCKY)
			BEGIN
				SELECT KT = 1
			END
		ELSE
			BEGIN
				SELECT KT = 0
			END
END
GO


