CREATE PROC SP_DANGNHAP
@TENLOGIN NVARCHAR (50)

AS
BEGIN
	DECLARE @TENUSER NVARCHAR(50)
	SELECT @TENUSER=NAME FROM sys.sysusers WHERE sid = SUSER_SID(@TENLOGIN)
 

	DECLARE @TENNHOM NVARCHAR(50)
	SELECT @TENNHOM = NAME  FROM sys.sysusers 
	WHERE UID = (SELECT GROUPUID 
                 FROM SYS.SYSMEMBERS 
                   WHERE MEMBERUID= (SELECT UID FROM sys.sysusers 
                                      WHERE NAME=@TENUSER))

	SELECT USERNAME = @TENUSER, 
		HOTEN = (SELECT HO+ ' '+ TEN FROM GIANGVIEN  WHERE MAGV = @TENUSER ),
		TENNHOM=@TENNHOM
END

GO