USE [QLDSV_TC]
GO

CREATE PROC SP_CHECK_TAOMONHOC
    @MAMH  NCHAR(10),
    @TENMH NVARCHAR(50)
AS
BEGIN
    DECLARE @MAMH_TRIM NVARCHAR(10);
    SET @MAMH_TRIM = LTRIM(RTRIM(@MAMH));

    IF EXISTS (SELECT 1 FROM MONHOC WHERE MAMH = @MAMH_TRIM)
    BEGIN
        RAISERROR( N'Mã môn học "%s" đã tồn tại!',16, 1, @MAMH_TRIM);
        RETURN;
    END

    DECLARE @TENMH_TRIM NVARCHAR(10);
    SET @TENMH_TRIM = LTRIM(RTRIM(@TENMH));

    IF EXISTS (SELECT 1 FROM MONHOC WHERE TENMH = @TENMH_TRIM)
    BEGIN
        RAISERROR(N'Tên môn học "%s" đã tồn tại!',16, 1,@TENMH_TRIM);
        RETURN;
    END
END
GO


