USE [QLDSV_TC]
GO

CREATE PROC SP_CHECK_CAPNHATMONHOC
    @TENMH NVARCHAR(50)
AS
BEGIN
    DECLARE @TENMH_TRIM NVARCHAR(50);
    SET @TENMH_TRIM = LTRIM(RTRIM(@TENMH));

    IF EXISTS (SELECT 1 FROM MONHOC WHERE TENMH = @TENMH_TRIM)
    BEGIN
        RAISERROR(N'Tên môn học "%s" đã tồn tại!', 16, 1, @TENMH_TRIM);
        RETURN;
    END
END
GO


